### ISSUE TITLE
Limit Submission Output Size

### ISSUE THREAD

**Issue by eriq-augustine** [edulinq/autograder-server#20]
Right now, we just carry around the output from a students submission grading in memory.
And infinite loop could blow us up.

We need to put restrictions on how much output we will allow (10MB?).

How exactly to implement this could be either easy or hard.
If we are lucky, then we can just used a fixed size byte array as the writer for output from the docker container and if the write fails, we have too much output.
If we are unlucky, then we can't do that and we may have to do something like regularly check the buffer usage.

**Comment by eriq-augustine** [comment]
Make sure to also check the grading result (the json output by the grader).
Aside from having an unlimited number of questions, we also allow some arbitrary fields.

**Comment by cfbeard** [comment]
Taking on this one.

**Comment by eriq-augustine** [comment]
@cfbeard is actually currently tackling #19, with plans to move onto this after.

**Comment by eriq-augustine** [comment]
This is complete in 40817258b147237cbfacd917aa6d853a174be98e.
