### ISSUE TITLE
feature request: grace periods for assignment submissions

### ISSUE THREAD

**Issue by lkuper** [edulinq/autograder-server#70]
Traditionally, CSE114A has had a certain number of "grace days" that students can use for assignment submissions at any point in the quarter.  An example grace day policy is: "You have a total of four late days that you can use throughout the quarter as you need them. A late day means anything between 1 second and 23 hours 59 minutes and 59 seconds past a deadline."

The exact semantics of that policy (where using any part of a grace day uses up the whole grace day) might be annoying to implement; I'd be fine with just giving each student a counter with 24 * N hours for the whole quarter, where N is the number of grace days.

While Gradescope has *per-assignment* "late due dates", it actually doesn't support fungible-between-assignments grace days like this, so if EriqGrader supported this feature, it'd be an advantage over Gradescope.  (With Gradescope, if we cared about precise accounting of the total number of grace days taken, we would need to do the accounting manually.  We mostly don't care, but.)

Requires #36.

**Comment by eriq-augustine** [comment]
We actually already have this, but don't have documentation out for it yet.
For now, we can touch base synchronously, the documentation will come with the big UI push this summer.
